#
# LuaDist Travis-CI Hook
#

# We assume Fortran build environments
language: Fortran
	
# Try using multiple Lua Implementations
env:
  - TOOL=""                     # Use native compiler (GCC usually)

# Install dependencies
install:
  - git clone git://github.com/LuaDist/_util.git ~/_util
  - ~/_util/travis install

# Bootstap
before_script:
  - ~/_util/travis bootstrap

# Build the module
script:
  - ~/_util/travis build

# Execute additional tests or commands
#after_script:
#  - ~/_util/travis test

# Only watch the master branch
branches:
  only:
    - master

# Notify the LuaDist Dev group if needed
notifications:
  recipients:
    - luadist-dev@googlegroups.com
  email:
    on_success: change
    on_failure: always
